[package]
name = "ea-big"
version = "0.1.1"
authors = ["Capucho <jcapucho7@gmail.com>"]
edition = "2018"
description = """
A library to open ea .big game files
"""
readme = "README.md"
repository = "https://github.com/JCapucho/ea-big"
license = "MIT"

[dependencies]
